### ISSUE TITLE
作者，您好。请问您有可视化生成的视差图吗？请问怎么可视化

### ISSUE THREAD

**Issue by huangcimu** [zhixuanli/StereoNet#11]

**Comment by zhixuanli** [comment]
抱歉，目前没有做可视化部分，不太清楚

**Comment by huangcimu** [comment]
好的，谢谢您！还有一个问题，在sceneflow数据上面进行预训练的时候,我训练了20个epoch，loss为4.6，没有您的效果好！请问您做预训练的时候训练了多少个epoch------------------ 原始邮件 ------------------
发件人: "zhixuanli"<notifications@github.com>
发送时间: 2019年6月13日(星期四) 下午2:35
收件人: "zhixuanli/StereoNet"<StereoNet@noreply.github.com>;
抄送: "huangcimu"<527354782@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [zhixuanli/StereoNet] 作者，您好。请问您有可视化生成的视差图吗？请问怎么可视化 (#11)



抱歉，目前没有做可视化部分，不太清&#x695A;
 
&mdash;

**Comment by zhixuanli** [comment]
预训练也是20个epoch
下面是我的电脑上所有的文件，包括预训练模型
--------------------------------
Link:
https://pan.baidu.com/s/1gfGR8AUmA-I0HqzEtHrqow

Key:
jpz3

This is the whole project and files on my PC.

**Comment by huangcimu** [comment]
OK，谢谢您


发自我的iPhone

------------------ 原始邮件 ------------------
发件人: zhixuanli <notifications@github.com>
发送时间: 2019年6月13日 14:46
收件人: zhixuanli/StereoNet <StereoNet@noreply.github.com>
抄送: huangcimu <527354782@qq.com>, Author <author@noreply.github.com>
主题: 回复：[zhixuanli/StereoNet] 作者，您好。请问您有可视化生成的视差图吗？请问怎么可视化 (#11)

**Comment by zhixuanli** [comment]
请问您用的手机端浏览github的软件是什么？
看起来很方便

**Comment by huangcimu** [comment]
一般我浏览github用UC浏览器

**Comment by zhixuanli** [comment]
谢谢您！
