### ISSUE TITLE
cost_volume.py中是对左图的feature map进行右移吗？

### ISSUE THREAD

**Issue by cty2324** [zhixuanli/StereoNet#5]
按照我的理解，左图中的一个点对应右图的同名点，应该是x坐标更大。这样的话对左图的feature map进行右移不就会更加拉开距离了吗？是不是应该对右图的feature map进行右移呢？

当前你的代码中是对左图的feature map进行了右移操作：
 right_move = torch.cat((zero_padding, origin), 3)

这里我有点拿不准这样做的意图，所以希望能得到你的指教，谢谢：）

**Comment by zhixuanli** [comment]
您好，您的理解是正确的，的确应该是左图向左移动，在右侧添加padding。

这是一个立体匹配里的基本问题，我对这个领域接触不深，当时为了赶作业匆匆写完代码，挖了许多坑，让您见笑了 😭 

一会我就去改过来，并重新训练

Reference: [https://github.com/liuruijin17/GCNet-tensorflow/blob/master/cost_volume.py](https://github.com/liuruijin17/GCNet-tensorflow/blob/master/cost_volume.py)

**Comment by cty2324** [comment]
很高兴能帮到你，你的代码也给了我很多帮助，谢谢~

**Comment by zhixuanli** [comment]
@cty2324 :smile:
