### ISSUE TITLE
有个问题

### ISSUE THREAD

**Issue by XAB745220zt** [zhixuanli/StereoNet#7]
您好，谢谢你回复我，现在我想知道，这个如何训练，听您的介绍，它需要先在光流数据集上，然后在kitti2015上微调，可以详细告诉我吗，还有我像用它来返回真实的三维坐标，比如测距，我该如何实现它

**Comment by zhixuanli** [comment]
您好，我是根据论文进行的实验设置。在论文中，网络需要现在较大的数据集上预训练，然后再在kitti上finetune。
这里并没有用到较大数据集的光流信息，只是作为很多pair进行输入。本质上和kitti的区别不是很大。
第二个问题我暂时不清楚，调查后再回复您

**Comment by zhixuanli** [comment]
预训练和微调的代码都在仓库中，是根据PSMNet改编的

**Comment by zhixuanli** [comment]
您好，这份代码主要是为了做两个图像在x方向上的匹配的（y方向已经校准）。

PSMNet的官方代码也是在计算两个图的disparity: https://github.com/JiaRenChang/PSMNet
可以参考其REAME中的这3张图：

![](https://camo.githubusercontent.com/3e43de5181aae60499dedb32640fdf2e92d0d324/687474703a2f2f7777772e63766c6962732e6e65742f64617461736574732f6b697474692f726573756c74732f656662396462393739333865313261323062396339356365353933663633336464363361323734342f696d6167655f302f3030303030345f31302e706e67)

![](https://camo.githubusercontent.com/173dbcc4ab993afce09839c1435524748b180b34/687474703a2f2f7777772e63766c6962732e6e65742f64617461736574732f6b697474692f726573756c74732f656662396462393739333865313261323062396339356365353933663633336464363361323734342f726573756c745f646973705f696d675f302f3030303030345f31302e706e67)

![](https://camo.githubusercontent.com/9ef7b620927a5e83318e44f68618b8bfa5f24815/687474703a2f2f7777772e63766c6962732e6e65742f64617461736574732f6b697474692f726573756c74732f656662396462393739333865313261323062396339356365353933663633336464363361323734342f6572726f72735f646973705f696d675f302f3030303030345f31302e706e67)

对于测距，能得出图片中的各个点距离像平面的距离，可以看作是一种相对坐标。
其领域的关键词应该是DepthEstimation (+ Stereo)
可以参考以下链接的内容：
+ https://github.com/topics/depth-estimation
+ https://github.com/johannesu/stereo

#### 从disparity到depth：

+ https://github.com/IntelRealSense/librealsense/blob/master/doc/depth-from-stereo.md

其中
```
import numpy
import cv2

fx = 942.8          # lense focal length
baseline = 54.8     # distance in mm between the two cameras
disparities = 128   # num of disparities to consider
block = 31          # block size to match
units = 0.001       # depth units

sbm = cv2.StereoBM_create(numDisparities=disparities,
                          blockSize=block)

disparity = sbm.compute(left, right)

depth = np.zeros(shape=left.shape).astype(float)
depth[disparity > 0] = (fx * baseline) / (units * disparity[disparity > 0])
```

最后三行应该是您想要的结果。

**Comment by XAB745220zt** [comment]
谢谢您的回复，你真的是个优秀又不错的人，我会好好研究一下。

**Comment by XAB745220zt** [comment]
![image](https://user-images.githubusercontent.com/35139578/55602604-03fc7400-5799-11e9-972d-49ee689ad829.png)
我不知道下载哪个数据集，还有需要制作自己的数据集吗

**Comment by XAB745220zt** [comment]
对不起我真的不好意思再问你，但是我又想弄懂它，比如下载kitti的数据集，该下载哪一个
![image](https://user-images.githubusercontent.com/35139578/55602696-75d4bd80-5799-11e9-8aa8-7b2c7ffaf71b.png)

**Comment by zhixuanli** [comment]
@XAB745220zt 您好，感谢称赞，我其实对立体匹配不是非常熟悉，这份代码是上学期的一个课程作业。所以了解有限，我也尽力而为。

对于Scene Flow数据集，有三个种类，可以都下载下来，但是数据量非常的大。

需要下载：
+ 训练数据：RGB Images(clean pass)
+ Ground Truth: Disparity （下面区域的第一行的）

对于Kitti，需要下载2GB那个

**Comment by XAB745220zt** [comment]
谢谢·您，对于kitti我是下载stero还是SceneFlow

**Comment by zhixuanli** [comment]
您好，没太明白您的意思。对于Kitti应该下载2GB那个：http://www.cvlibs.net/download.php?file=data_scene_flow.zip

**Comment by XAB745220zt** [comment]
Thank you. I just don't understand where I've circled it。
Thank you. I am also a student. I don't know what my major is in this field，i like it .
![Inked55602696-75d4bd80-5799-11e9-8aa8-7b2c7ffaf71b_LI](https://user-images.githubusercontent.com/35139578/55627849-bbb57400-57e1-11e9-8053-a98417ad0a49.jpg)

**Comment by zhixuanli** [comment]
You are welcome. Interest is really important in research, especially when we go deep and far away. It's happy to know that I can help you!

**Comment by XAB745220zt** [comment]
Unfortunately, my undergraduate degree is mechanical, but I don’t have much interest in this major.

**Comment by zhixuanli** [comment]
Good luck!

**Comment by koalaaaaaaaaa** [comment]
笑死，一会中文一会英文，整乐了
