### ISSUE TITLE
the trained model

### ISSUE THREAD

**Issue by alphaccw** [zhixuanli/StereoNet#9]
Thank you for sharing the code.
Is it possible for you to share the pre-trained model on sceneflow data?

**Comment by zhixuanli** [comment]
Link: 
https://pan.baidu.com/s/1gfGR8AUmA-I0HqzEtHrqow 

Key: 
jpz3 

This is the whole project and files on my PC.

**Comment by alphaccw** [comment]
thank you for sharing :)

**Comment by zhixuanli** [comment]
You are welcome!
